### ISSUE TITLE
Initial todos

### ISSUE THREAD

**Issue by nicholaswmin** [TheProfs/asset-bucket#1]
## Todos A

- [x] `paper-menu-button` doesn't render. Find another way or fix
- [x] Due to probably vulcanisation in the parent project (where this element would be included), PDF.js cannot find the PDF.JS worker file. Referencing PDF.js from a CDN works though
- [x] Selecting an item via the `asset-list` should fire an event, `item-selected` - after the item has been pulled from `media-cachier`
- [x] ~~Ensure `bower_component` imports don't conflict with existing imports in parent projects (where this element would be installed) and most importantly that dupe imports don't get downloaded *twice*.~~ We don't really care about this, parent projects are expected to bundle/vulcanise their elements to de-dupe their dependencies.
- [x] `pdf-to-image` should be installed from Bower - remove `lib/` directory

## Todos B

- [x] Add loading prop whilst XHR is in-flight
- [x] Add an indicator that a file was added, either flash the menu button or open the whole `asset-list`
- [x] The API shouldn't differentiate between PDF's and Images. It should expose a single method, e.g `addFile(fileObj)` where some MIME detection occurs and the appropriate course is taken
- [x] Ensure it works and that tests pass when ShadowDOM is used
- [x] Ensure element does not receive initial and unnecessary focus when no `items exist`
