### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by nicholaswmin** [TheProfs/asset-bucket#2]
## Todos

- [ ] Add documentation, both Polymer element documentation and README 
- [ ] Run over code with `$ polymer lint` and integrate linting in CI tests
- [ ] Do a Github release
- [ ] Release on Bower and add bower installation link in README
